asymmetric_obs: True
params:
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    separate: True
    name: actor_critic
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
#          name: default
          name: variance_scaling_initializer
          scale: 0.02
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True

    mlp:
      units: [400, 200, 100]
      activation: elu
      d2rl: False

      initializer:
        name: default
        scale: 2
      regularizer:
        name:  'None'

  load_checkpoint: False
  load_path: nn/weights.pth

  config:
    name: 'trifinger'
    env_name: rlgpu
    ppo: True
    normalize_input: False
    reward_shaper:
      scale_value: 0.01
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 3e-4
    lr_schedule: adaptive
    lr_threshold: 0.008
    score_to_win : 1000000
    max_epochs: 100000
    save_best_after: 500
    save_frequency: 100
    preemption_checkpoint_freq: 500
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    steps_num: 32
    minibatch_size: 8192 #16384
    mini_epochs: 4
    critic_coef: 4
    clip_value: False
    seq_len: 4
    bounds_loss_coef: 0.0001

    central_value_config:
      seq_length: 4
      minibatch_size: 8192 #16384
      mini_epochs: 4
      lr: 5e-4
      clip_value: False
      normalize_input: False
      grad_norm: 1.0
      truncate_grads: True
      network:
        name: actor_critic
        central_value: True
        mlp:
          units: [400, 200, 100]
          activation: elu
          d2rl: False
          initializer:
            #name: default
            name: variance_scaling_initializer
            scale: 2
          regularizer:
            name:  'None'